# -*- coding: utf-8 -*-
"""
Egypt Mega Scraper - Wikipedia API
100 places per category:
historical, museum, hotel, nature, market, beach, desert, religious, cruise
"""
import sys, time, random, re, json, pyodbc, requests
from deep_translator import GoogleTranslator

sys.stdout.reconfigure(encoding='utf-8')

DB_CONN_STR = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost,1433;DATABASE=DiscoverEgypt;"
    "UID=sa;PWD=YourPassword123!;TrustServerCertificate=yes;"
)

WIKI_API    = "https://en.wikipedia.org/w/api.php"
COMMONS_API = "https://commons.wikimedia.org/w/api.php"
HEADERS = {'User-Agent': 'DiscoverEgyptApp/1.0 (contact@discover-egypt.com)'}

TARGET = 100

TAGS_MAP = {
    'historical': 'history,ancient,culture,Egypt,heritage,pharaonic',
    'museum':     'museum,culture,history,Egypt,art,antiquities',
    'hotel':      'accommodation,stay,hotel,Egypt,luxury',
    'nature':     'nature,wildlife,parks,Egypt,outdoors,scenery',
    'market':     'shopping,bazaar,market,Egypt,souvenirs,crafts',
    'beach':      'beach,sea,swimming,Egypt,coast,snorkeling',
    'desert':     'desert,safari,adventure,Egypt,dunes,oasis',
    'religious':  'mosque,church,temple,religion,Egypt,spiritual',
    'cruise':     'nile,cruise,boat,Egypt,river,sailing,felucca',
}

OPEN_MAP = {
    'hotel':  ('00:00', '23:59'),
    'market': ('09:00', '21:00'),
    'beach':  ('06:00', '20:00'),
    'cruise': ('07:00', '22:00'),
}

GOV_MAP = {
    'cairo':'Cairo','giza':'Giza','luxor':'Luxor','aswan':'Aswan',
    'alexandria':'Alexandria','sharm':'South Sinai','hurghada':'Red Sea',
    'dahab':'South Sinai','el gouna':'Red Sea','marsa alam':'Red Sea',
    'sinai':'South Sinai','red sea':'Red Sea','siwa':'Matrouh',
    'white desert':'New Valley','bahariya':'Giza','fayoum':'Fayoum',
    'suez':'Suez','ismailia':'Ismailia','port said':'Port Said',
    'safaga':'Red Sea','makadi':'Red Sea','sahl hasheesh':'Red Sea',
    'nubian':'Aswan','nile':'Cairo','mediterranean':'Alexandria',
    'sinai peninsula':'South Sinai',
}

# ─────────────────────────────────────────────────────────────────────────────
# PLACES LIST  (category, governorate, wikipedia_title)
# ─────────────────────────────────────────────────────────────────────────────
EGYPT_PLACES = [
# ══════════════════════════ HISTORICAL (100) ══════════════════════════════
('historical','Giza',        'Giza pyramid complex'),
('historical','Giza',        'Great Sphinx of Giza'),
('historical','Giza',        'Pyramid of Khufu'),
('historical','Giza',        'Pyramid of Khafre'),
('historical','Giza',        'Pyramid of Menkaure'),
('historical','Cairo',       'Cairo Citadel'),
('historical','Cairo',       'Khan el-Khalili'),
('historical','Cairo',       'Al-Azhar Mosque'),
('historical','Cairo',       'Mosque of Ibn Tulun'),
('historical','Cairo',       'Al-Muizz Street'),
('historical','Cairo',       'Hanging Church Cairo'),
('historical','Cairo',       'Ben Ezra Synagogue'),
('historical','Cairo',       'Coptic Cairo'),
('historical','Cairo',       'Mosque of Muhammad Ali, Cairo'),
('historical','Cairo',       'Bab Zuweila'),
('historical','Cairo',       'Nilometer'),
('historical','Cairo',       'Abdeen Palace'),
('historical','Cairo',       'Manial Palace'),
('historical','Cairo',       'Mosque of Amr ibn al-As'),
('historical','Cairo',       'Fustat'),
('historical','Luxor',       'Karnak'),
('historical','Luxor',       'Luxor Temple'),
('historical','Luxor',       'Valley of the Kings'),
('historical','Luxor',       'Mortuary Temple of Hatshepsut'),
('historical','Luxor',       'Valley of the Queens'),
('historical','Luxor',       'Colossi of Memnon'),
('historical','Luxor',       'Medinet Habu'),
('historical','Luxor',       'Ramesseum'),
('historical','Luxor',       'Temple of Seti I'),
('historical','Luxor',       'Dendera Temple complex'),
('historical','Luxor',       'Abydos, Egypt'),
('historical','Aswan',       'Abu Simbel temples'),
('historical','Aswan',       'Philae temple'),
('historical','Aswan',       'Kom Ombo'),
('historical','Aswan',       'Edfu'),
('historical','Aswan',       'Elephantine'),
('historical','Aswan',       'Aswan Dam'),
('historical','Aswan',       'Temple of Kalabsha'),
('historical','Alexandria',  "Pompey's Pillar"),
('historical','Alexandria',  'Catacombs of Kom el Shoqafa'),
('historical','Alexandria',  'Citadel of Qaitbay'),
('historical','Alexandria',  'Bibliotheca Alexandrina'),
('historical','Alexandria',  'Montazah Palace'),
('historical','Alexandria',  'Abu al-Abbas al-Mursi Mosque'),
('historical','Sinai',       'Mount Sinai'),
('historical','Sinai',       "Saint Catherine's Monastery"),
('historical','Sinai',       'Colored Canyon, Egypt'),
('historical','Cairo',       'Bab el-Futuh'),
('historical','Cairo',       'Gate of Bab al-Nasr, Cairo'),
('historical','Cairo',       'Al-Rifa\'i Mosque'),
('historical','Luxor',       'Temple of Khnum at Esna'),
('historical','Luxor',       'Luxor Museum'),
('historical','Luxor',       'Tombs of the Nobles, Luxor'),
('historical','Aswan',       'Nubian villages'),
('historical','Fayoum',      'Pyramid of Meidum'),
('historical','Fayoum',      'Pyramid of Hawara'),
('historical','Giza',        'Step Pyramid of Djoser'),
('historical','Giza',        'Pyramid of Unas'),
('historical','Giza',        'Memphis, Egypt'),
('historical','Cairo',       'Egyptian Museum, Cairo'),
('historical','Cairo',       'Gayer-Anderson Museum'),
('historical','Cairo',       'Al-Hakim Mosque'),
('historical','Cairo',       'Al-Mu\'ayyad Mosque'),
('historical','Sinai',       'Taba, Egypt'),
('historical','Suez',        'Suez Canal'),
('historical','Ismailia',    'Ismailia, Egypt'),
('historical','Red Sea',     'Hurghada, Egypt'),
('historical','South Sinai', 'Dahab, Egypt'),
('historical','Cairo',       'Qasr el-Nil Bridge'),
('historical','Cairo',       'Tahrir Square'),
('historical','Cairo',       'Al-Azhar University'),
('historical','Alexandria',  'Greco-Roman Museum, Alexandria'),
('historical','Alexandria',  'Stanley Bridge, Alexandria'),
('historical','Luxor',       'Valley of the Artisans'),
('historical','Aswan',       'Agha Khan Mausoleum'),
('historical','Aswan',       'Sobek'),
('historical','Fayoum',      'Karanis, Egypt'),
('historical','Cairo',       'Mosque-Madrassa of Sultan Hassan'),
('historical','Cairo',       'Mosque of al-Nasir Muhammad'),
('historical','Cairo',       "Saladin's Cairo"),
('historical','Giza',        'Abu Sir pyramids'),
('historical','Giza',        'Dahshur'),
('historical','Luxor',       'Malkata'),
('historical','Sinai',       'Serabit el-Khadim'),
('historical','Red Sea',     'Mons Claudianus'),
('historical','Matrouh',     'Siwa Oasis'),
('historical','Matrouh',     'Temple of the Oracle, Siwa'),
('historical','New Valley',  'Dakhla Oasis'),
('historical','New Valley',  'Kharga Oasis'),
('historical','New Valley',  'Farafra'),
('historical','Alexandria',  'Serapeum of Alexandria'),
('historical','Luxor',       'Habu'),
('historical','Aswan',       'Wadi al-Subua'),
('historical','Cairo',       'Mosque of al-Aqmar'),
('historical','Cairo',       'Wikala of al-Ghuri'),
('historical','Cairo',       'Bayt al-Suhaymi'),
('historical','Cairo',       'Sabil-Kuttab of Katkhuda'),
('historical','Cairo',       'Khayrbak Complex'),
('historical','Sinai',       'Nuweiba'),
('historical','Suez',        'Port Tawfiq'),

# ══════════════════════════ MUSEUM (100) ══════════════════════════════════
('museum','Cairo',       'Egyptian Museum, Cairo'),
('museum','Cairo',       'National Museum of Egyptian Civilization'),
('museum','Cairo',       'Museum of Islamic Art, Cairo'),
('museum','Cairo',       'Coptic Museum, Cairo'),
('museum','Cairo',       'Gayer-Anderson Museum'),
('museum','Cairo',       'Manial Palace Museum'),
('museum','Cairo',       'Abdeen Palace Museum'),
('museum','Cairo',       'Egyptian Textile Museum'),
('museum','Cairo',       'Mahmoud Khalil Museum'),
('museum','Cairo',       'Agricultural Museum, Cairo'),
('museum','Cairo',       'Geological Museum, Cairo'),
('museum','Cairo',       'Cairo Opera House'),
('museum','Cairo',       'Postal Museum, Cairo'),
('museum','Cairo',       'Egyptian Military Museum'),
('museum','Cairo',       'Police Museum, Cairo'),
('museum','Cairo',       'Pharaonic Village'),
('museum','Cairo',       'Dokki Agricultural Museum'),
('museum','Cairo',       'Palace of Baron Empain'),
('museum','Cairo',       'Marriette Pasha Museum'),
('museum','Giza',        'Solar Boat Museum'),
('museum','Giza',        'Grand Egyptian Museum'),
('museum','Giza',        'Site Museum of the Pyramid of Khufu'),
('museum','Luxor',       'Luxor Museum'),
('museum','Luxor',       'Mummification Museum'),
('museum','Luxor',       'Carter House'),
('museum','Luxor',       'Luxor Art Museum'),
('museum','Aswan',       'Nubian Museum'),
('museum','Aswan',       'Aswan Museum'),
('museum','Aswan',       'Kitchener\'s Island'),
('museum','Alexandria',  'National Museum of Alexandria'),
('museum','Alexandria',  'Greco-Roman Museum, Alexandria'),
('museum','Alexandria',  'Royal Jewelry Museum, Alexandria'),
('museum','Alexandria',  'Bibliotheca Alexandrina'),
('museum','Alexandria',  'Shalabi Museum'),
('museum','Alexandria',  'Maritime Museum, Alexandria'),
('museum','Red Sea',     'Hurghada Grand Aquarium'),
('museum','Sinai',       'Sharm El-Sheikh Museum'),
('museum','Cairo',       'Saad Zaghloul Museum'),
('museum','Cairo',       'Mohamed Mahmoud Khalil Museum'),
('museum','Cairo',       'Museum of Egyptian Modern Art'),
('museum','Cairo',       'Entomology Museum, Cairo'),
('museum','Cairo',       'Egyptian Centre for International Cultural Cooperation'),
('museum','Fayoum',      'Fayoum Museum'),
('museum','Ismailia',    'Ismailia Museum'),
('museum','Suez',        'Suez Canal Museum'),
('museum','Cairo',       'Museum of Ancient Egyptian Art'),
('museum','Cairo',       'Egyptian National Railway Museum'),
('museum','Cairo',       'National Library and Archives of Egypt'),
('museum','Cairo',       'Cairo Zoo'),
('museum','Giza',        'Wax Museum, Giza'),
('museum','Luxor',       'Karnak Open Air Museum'),
('museum','Aswan',       'Elephantine Island Museum'),
('museum','Alexandria',  'Cavafy Museum'),
('museum','Alexandria',  'Contemporary Arts Center, Alexandria'),
('museum','Hurghada',    'Hurghada Museum'),
('museum','Cairo',       'Gezirah Arts Center'),
('museum','Cairo',       'House of Egyptian Architecture'),
('museum','Cairo',       'Townhouse Gallery, Cairo'),
('museum','Cairo',       'Zamalek Art Gallery'),
('museum','Cairo',       'Hanager Arts Center'),
('museum','Cairo',       'Museum of the Egyptian People\'s Assembly'),
('museum','Luxor',       'Visitor Centre at Karnak'),
('museum','Aswan',       'High Dam Museum'),
('museum','Cairo',       'Egyptian Islamic Arts Museum'),
('museum','Cairo',       'Museum of Hygiene'),
('museum','Cairo',       'Natural History Museum, Cairo'),
('museum','Cairo',       'Geological Survey of Egypt'),
('museum','Cairo',       'Coin Museum, Cairo'),
('museum','Giza',        'Pyramid of Unas Museum'),
('museum','Luxor',       'Medinet Habu Visitor Center'),
('museum','Aswan',       'Philae Museum'),
('museum','Alexandria',  'Fine Arts Museum, Alexandria'),
('museum','Alexandria',  'Antoniadis Gardens Museum'),
('museum','Cairo',       'Museum of the Egyptian Revolution'),
('museum','Fayoum',      'Karanis Museum'),
('museum','Cairo',       'Stained Glass Museum, Cairo'),
('museum','Cairo',       'Children\'s Museum, Cairo'),
('museum','Red Sea',     'Sindbad Aquarium'),
('museum','Cairo',       'Sennari House'),
('museum','Cairo',       'Darb 1718'),
('museum','Cairo',       'Museum of Islamic Ceramics, Cairo'),
('museum','Cairo',       'Mevlevi Tekke Museum'),
('museum','Cairo',       'Cairo Tower'),
('museum','Luxor',       'Deir el-Medina Museum'),
('museum','Aswan',       'Aga Khan Mausoleum Museum'),
('museum','Luxor',       'Amenhotep III Temple'),
('museum','Cairo',       'Egyptian Exhibition Museum'),
('museum','Giza',        'Memphis Museum'),
('museum','Cairo',       'Museum of Egyptian Stamps'),
('museum','Cairo',       'Saqqara Visitor Center'),
('museum','Cairo',       'International Museum of Children\'s Art'),
('museum','Cairo',       'National Gallery of Egyptian Art'),
('museum','Cairo',       'Photography Museum, Cairo'),
('museum','Hurghada',    'Red Sea Environmental Center'),
('museum','Cairo',       'Opera Square Museum'),
('museum','Cairo',       'War Museum, Cairo'),

# ══════════════════════════ HOTEL (100) ═══════════════════════════════════
('hotel','Cairo',        'Cairo Marriott Hotel'),
('hotel','Cairo',        'Four Seasons Hotel Cairo at Nile Plaza'),
('hotel','Cairo',        'Sofitel Cairo El Gezirah'),
('hotel','Cairo',        'Kempinski Nile Hotel Cairo'),
('hotel','Cairo',        'InterContinental Cairo Semiramis'),
('hotel','Cairo',        'Conrad Cairo'),
('hotel','Cairo',        'The Nile Ritz-Carlton, Cairo'),
('hotel','Cairo',        'Hilton Cairo Zamalek Residences'),
('hotel','Cairo',        'Ramses Hilton Hotel'),
('hotel','Cairo',        'Fairmont Nile City Hotel'),
('hotel','Cairo',        'Four Seasons Hotel Cairo at The First Residence'),
('hotel','Cairo',        'Steigenberger Hotel El Tahrir Cairo'),
('hotel','Cairo',        'Cairo Pyramids Hotel'),
('hotel','Cairo',        'Grand Nile Tower Hotel'),
('hotel','Giza',         'Marriott Mena House'),
('hotel','Giza',         'Le Méridien Pyramids Hotel & Spa'),
('hotel','Giza',         'Movenpick Hotel Cairo Media City'),
('hotel','Hurghada',     'Steigenberger Aqua Magic'),
('hotel','Hurghada',     'Coral Beach Resort Hurghada'),
('hotel','Hurghada',     'Marriott Hurghada Beach Resort'),
('hotel','Hurghada',     'Hilton Hurghada Plaza'),
('hotel','Hurghada',     'SUNRISE Grand Select Arabian Beach Resort'),
('hotel','Hurghada',     'Pickalbatros Aqua Park Resort'),
('hotel','Hurghada',     'Sheraton Soma Bay Resort'),
('hotel','Hurghada',     'Jaz Aquamarine Resort'),
('hotel','Hurghada',     'Rixos Premium Seagate'),
('hotel','Hurghada',     'Albatros Aqua Park Resort'),
('hotel','Hurghada',     'Baron Palace Hurghada'),
('hotel','Hurghada',     'Titanic Beach Spa & Aqua Park'),
('hotel','Sharm El Sheikh','Hilton Sharm Dreams Resort'),
('hotel','Sharm El Sheikh','Grand Rotana Resort & Spa'),
('hotel','Sharm El Sheikh','Reef Oasis Blue Bay Resort'),
('hotel','Sharm El Sheikh','Hyatt Regency Sharm El Sheikh Resort'),
('hotel','Sharm El Sheikh','Marriott Sharm El Sheikh Mountain Resort'),
('hotel','Sharm El Sheikh','Rixos Sharm El Sheikh'),
('hotel','Sharm El Sheikh','Four Seasons Resort Sharm El Sheikh'),
('hotel','Sharm El Sheikh','Movenpick Resort Sharm El Sheikh'),
('hotel','Sharm El Sheikh','Charmillion Club Aqua Park'),
('hotel','Sharm El Sheikh','Jaz Mirabel Beach Hotel'),
('hotel','Sharm El Sheikh','Coral Sea Aqua Club'),
('hotel','Dahab',        'Nesima Resort Dahab'),
('hotel','Dahab',        'Hilton Dahab Resort'),
('hotel','Dahab',        'Novotel Dahab Holiday Resort'),
('hotel','El Gouna',     'Steigenberger Golf Resort El Gouna'),
('hotel','El Gouna',     'Three Corners Ocean View El Gouna'),
('hotel','El Gouna',     'Movenpick Resort El Gouna'),
('hotel','El Gouna',     'Sheraton Miramar Resort El Gouna'),
('hotel','Red Sea',      'Serenity Alpha Beach'),
('hotel','Red Sea',      'Cleopatra Luxury Resort Makadi'),
('hotel','Red Sea',      'Baron Palace Sahl Hasheesh'),
('hotel','Red Sea',      'AJIRA Resort Sahl Hasheesh'),
('hotel','Red Sea',      'Regency Plaza Aqua Park Safaga'),
('hotel','Red Sea',      'Royal Tulip Beach Resort Safaga'),
('hotel','Red Sea',      'Shams Alam Beach Resort Marsa Alam'),
('hotel','Red Sea',      'Orca Dive Club Marsa Alam'),
('hotel','Luxor',        'Sofitel Winter Palace Luxor'),
('hotel','Luxor',        'Steigenberger Nile Palace Luxor'),
('hotel','Luxor',        'Hilton Luxor Resort & Spa'),
('hotel','Luxor',        'Iberotel Luxor'),
('hotel','Luxor',        'Movenpick Resort Luxor'),
('hotel','Luxor',        'Sonesta St. George Hotel Luxor'),
('hotel','Aswan',        'Sofitel Legend Old Cataract Hotel'),
('hotel','Aswan',        'Movenpick Resort Aswan'),
('hotel','Aswan',        'Pyramisa Isis Island Resort Aswan'),
('hotel','Aswan',        'Basma Hotel Aswan'),
('hotel','Alexandria',   'Four Seasons Hotel Alexandria'),
('hotel','Alexandria',   'Marriott Alexandria Hotel'),
('hotel','Alexandria',   'Helnan Palestine Hotel'),
('hotel','Alexandria',   'Sofitel Cecil Hotel Alexandria'),
('hotel','Alexandria',   'Renaissance Alexandria Hotel'),
('hotel','Sinai',        'Taba Heights Beach & Golf Resort'),
('hotel','Sinai',        'Intercontinental Taba Heights'),
('hotel','Sinai',        'Sheraton Taba Heights Resort'),
('hotel','Cairo',        'Tolip Hotel Alexandria'),
('hotel','Cairo',        'Swissotel Cairo'),
('hotel','Cairo',        'Le Passage Cairo Hotel & Casino'),
('hotel','Cairo',        'Cairo Capital Club'),
('hotel','Cairo',        'Concorde El Salam Hotel Cairo'),
('hotel','Cairo',        'Atlas Zamalek Boutique Hotel'),
('hotel','Cairo',        'Pyramids Park Resort Cairo'),
('hotel','Cairo',        'Novotel Cairo Airport Hotel'),
('hotel','Cairo',        'Sheraton Cairo Hotel'),
('hotel','Cairo',        'Holiday Inn Cairo Citystars'),
('hotel','Hurghada',     'Serenity Fun City Resort'),
('hotel','Hurghada',     'Sultan Bey Hotel Hurghada'),
('hotel','Hurghada',     'Siva Port Ghalib Resort'),
('hotel','Hurghada',     'Sea Star Beau Rivage Resort'),
('hotel','Sharm El Sheikh','Naama Bay Promenade'),
('hotel','Sharm El Sheikh','Domina Coral Bay Hotel'),
('hotel','Sharm El Sheikh','Le Meridien Dahab Resort'),
('hotel','Red Sea',      'Three Corners Equinox Beach Hotel'),
('hotel','Red Sea',      'Radisson Blu Hotel Marsa Alam'),
('hotel','Fayoum',       'Auberge du Lac Fayoum'),
('hotel','Siwa',         'Siwa Shali Resort'),
('hotel','Siwa',         'Adrere Amellal Desert Ecolodge'),
('hotel','Luxor',        'Jaz Makadi Golf & Spa Resort Luxor'),
('hotel','Aswan',        'Nubian Rest House'),
('hotel','Cairo',        'Crowne Plaza West Cairo Arkan'),

# ══════════════════════════ NATURE (100) ══════════════════════════════════
('nature','Red Sea',     'Red Sea'),
('nature','South Sinai', 'Ras Muhammad National Park'),
('nature','Red Sea',     'Giftun Islands'),
('nature','South Sinai', 'Dahab, Egypt'),
('nature','Aswan',       'Aswan Botanical Garden'),
('nature','Aswan',       'Kitchener\'s Island'),
('nature','Fayoum',      'Wadi El Rayan'),
('nature','Fayoum',      'Birket Qarun'),
('nature','New Valley',  'White Desert National Park'),
('nature','New Valley',  'Black Desert, Egypt'),
('nature','Matrouh',     'Siwa Oasis'),
('nature','Red Sea',     'Wadi Hammamat'),
('nature','Red Sea',     'Wadi el-Gemal National Park'),
('nature','South Sinai', 'Nabq Protected Area'),
('nature','South Sinai', 'Tiran Island'),
('nature','South Sinai', 'Ras Abu Gallum'),
('nature','South Sinai', 'Blue Hole, Dahab'),
('nature','Red Sea',     'Abu Dabbab'),
('nature','South Sinai', 'Mount Catherine'),
('nature','South Sinai', 'Feiran Oasis'),
('nature','Aswan',       'Lake Nasser'),
('nature','Cairo',       'Wadi Degla Protectorate'),
('nature','Cairo',       'Al-Azhar Park'),
('nature','Cairo',       'Fish Garden, Cairo'),
('nature','Cairo',       'Cairo Zoological Garden'),
('nature','Giza',        'Giza Zoo'),
('nature','Fayoum',      'Fayoum Oasis'),
('nature','New Valley',  'Bahariya Oasis'),
('nature','New Valley',  'Dakhla Oasis'),
('nature','New Valley',  'Kharga Oasis'),
('nature','South Sinai', 'Colored Canyon'),
('nature','Aswan',       'Wadi Allaqi Biosphere Reserve'),
('nature','Red Sea',     'Hurghada coral reefs'),
('nature','South Sinai', 'Gulf of Aqaba'),
('nature','Mediterranean','Alexandria Corniche'),
('nature','Sinai',       'Sinai Peninsula'),
('nature','Red Sea',     'Marsa Alam coral reefs'),
('nature','Red Sea',     'El Quseir, Egypt'),
('nature','Matrouh',     'Mersa Matruh beach'),
('nature','Matrouh',     'Agiba Beach'),
('nature','Mediterranean','Sidi Abdel Rahman'),
('nature','Cairo',       'Qarun lake birds'),
('nature','South Sinai', 'Nuweiba, Egypt'),
('nature','Red Sea',     'Ras Banas'),
('nature','South Sinai', 'Ain Khudra'),
('nature','New Valley',  'Crystal Mountain Egypt'),
('nature','New Valley',  'Qasr Farafra'),
('nature','South Sinai', 'Ain Hudra Oasis'),
('nature','Luxor',       'Valley of the Kings'),
('nature','Aswan',       'Philae Island'),
('nature','Red Sea',     'Giftun Island'),
('nature','South Sinai', 'Fjord of Taba'),
('nature','Matrouh',     'El Alamein'),
('nature','Fayoum',      'Wadi Natrun'),
('nature','Cairo',       'Qanater Gardens'),
('nature','South Sinai', 'Wadi Feiran'),
('nature','Aswan',       'Sahara Forest Project'),
('nature','Red Sea',     'Sharm el-Naga'),
('nature','Cairo',       'Maadi Corniche'),
('nature','Red Sea',     'Magawish Island'),
('nature','South Sinai', 'St Catherine Protectorate'),
('nature','Aswan',       'Sehel Island'),
('nature','South Sinai', 'Sharm El Sheikh coral reefs'),
('nature','Luxor',       'Luxor Corniche'),
('nature','South Sinai', 'Wadi Ghazala'),
('nature','Red Sea',     'Quseir Old Town'),
('nature','New Valley',  'Ain Della'),
('nature','Matrouh',     'Qattara Depression'),
('nature','Giza',        'Saqqara Plateau'),
('nature','Fayoum',      'Whale Valley Wadi Al-Hitan'),
('nature','Aswan',       'Crocodile Island'),
('nature','Red Sea',     'Wadi el-Gemal'),
('nature','South Sinai', 'Ain Khudra Canyon'),
('nature','Cairo',       'Helwan Gardens'),
('nature','New Valley',  'Ain Della Oasis'),
('nature','Mediterranean','Ras el-Bar'),
('nature','Giza',        'Lake Mariout'),
('nature','Red Sea',     'Abu Menqar'),
('nature','South Sinai', 'Wadi Zaghra'),
('nature','Aswan',       'Salouga and Ghazal'),
('nature','Luxor',       'Birabi Gorge'),
('nature','New Valley',  'Nile Valley South'),
('nature','South Sinai', 'Gebel Banat'),
('nature','Red Sea',     'Mersa Shona'),
('nature','Matrouh',     'Siwa hot springs'),
('nature','Giza',        'Natrun Valley'),
('nature','Fayoum',      'Farafra White Desert'),
('nature','South Sinai', 'Wadi Nasb'),
('nature','Aswan',       'Lake Nuwaybi'),
('nature','Red Sea',     'Marsa Alam turtle watching'),
('nature','Sinai',       'Sinai Desert'),
('nature','Matrouh',     'Cleopatra Beach'),
('nature','Red Sea',     'Safaga coral gardens'),
('nature','South Sinai', 'Ras Nasrani'),
('nature','New Valley',  'Gilf Kebir National Park'),
('nature','Giza',        'Wadi el-Natrun monasteries'),
('nature','Fayoum',      'Tunis Village'),
('nature','New Valley',  'Ain Khudra Valley'),
('nature','Cairo',       'Zamalek Island'),
('nature','Matrouh',     'Marsa Matrouh Bay'),

# ══════════════════════════ MARKET (100) ══════════════════════════════════
('market','Cairo',       'Khan el-Khalili'),
('market','Cairo',       'Cairo Bazaar'),
('market','Luxor',       'Luxor Bazaar'),
('market','Aswan',       'Aswan Souk'),
('market','Alexandria',  'Al-Attarine Market, Alexandria'),
('market','Cairo',       'Tentmaker Street Cairo'),
('market','Cairo',       'Carpet Bazaar Cairo'),
('market','Cairo',       'Gold Market Cairo'),
('market','Cairo',       'Spice Market Cairo'),
('market','Cairo',       'Coppersmith Bazaar Cairo'),
('market','Cairo',       'Al-Muizz Street market'),
('market','Cairo',       'Rod El Farag Market'),
('market','Sharm El Sheikh','Sharm Old Market'),
('market','Sharm El Sheikh','Naama Bay Market'),
('market','Hurghada',    'Hurghada Bazaar'),
('market','Hurghada',    'Senzo Mall Hurghada'),
('market','Hurghada',    'Marina Mall Hurghada'),
('market','Cairo',       'City Stars Mall'),
('market','Cairo',       'Mall of Arabia Cairo'),
('market','Cairo',       'Cairo Festival City Mall'),
('market','Cairo','      Citystars Heliopolis'),
('market','Cairo',       'Wekala of el-Ghouri'),
('market','Cairo',       'Bein El-Kasrein Street'),
('market','Aswan',       'Nubian Craft Market'),
('market','Aswan',       'Aswan Ferial Market'),
('market','Luxor',       'East Bank Bazaar Luxor'),
('market','Luxor',       'Karnak Craft Shops'),
('market','Alexandria',  'Souk el Gomaa Alexandria'),
('market','Alexandria',  'Stanley Souk Alexandria'),
('market','Cairo',       'Antique Souk Cairo'),
('market','Cairo',       'Book Market Cairo Azbakeya'),
('market','Cairo',       'Leather Market Old Cairo'),
('market','Cairo',       'Weavers Market Cairo'),
('market','Sinai',       'Dahab Bazaar'),
('market','Sinai',       'Naama Bay Tourist Souk'),
('market','Red Sea',     'Port Ghalib Marina Mall'),
('market','Red Sea',     'Hurghada Grand Mall'),
('market','Cairo',       'Darb el-Ahmar Workshop'),
('market','Cairo',       'Attaba Market Cairo'),
('market','Cairo',       'Bashtil Market'),
('market','Cairo',       'Dokki Market'),
('market','Cairo',       'Mohandiseen Market'),
('market','Fayoum',      'Fayoum Pottery Market'),
('market','Fayoum',      'Fayoum Crafts Bazaar'),
('market','Luxor',       'Luxor Alabaster Shops'),
('market','Aswan',       'Aswan Papyrus Shop'),
('market','Cairo',       'Papyrus Art Cairo'),
('market','Cairo',       'Perfume Bazaar Cairo'),
('market','Cairo',       'Galleria 40 Mall'),
('market','Cairo',       'First Mall Giza'),
('market','Cairo',       'Arkadia Mall Cairo'),
('market','Cairo',       'Green Plaza Mall Alexandria'),
('market','Cairo',       'Talat Harb Street shops'),
('market','Cairo',       'Kasr El Nil Street'),
('market','Luxor',       'Luxor Temple Market'),
('market','Aswan',       'Ferial Gardens Market'),
('market','Alexandria',  'Korba Market'),
('market','Cairo',       'Wikalat Bazeraa'),
('market','Cairo',       'Suk el-Sagha Gold Market'),
('market','Cairo',       'Darb el-Barabra Market'),
('market','Cairo',       'Tuesday Bazaar Cairo'),
('market','Cairo',       'Animal Market Cairo'),
('market','Cairo',       'Flower Market Cairo'),
('market','Sinai',       'St Catherine Monastery Market'),
('market','Red Sea',     'Hurghada Artisan Village'),
('market','Sharm El Sheikh','Old Sharm Souk'),
('market','Cairo',       'Azbakiyya Garden Book Market'),
('market','Cairo',       'Al Fishawi Café Bazaar'),
('market','Cairo',       'Moez Street Crafts'),
('market','Aswan',       'Aswan Corniche Market'),
('market','Luxor',       'Winter Palace Bazaar'),
('market','Cairo',       'Suk el Fustat'),
('market','Cairo',       'Al Qahira Mall'),
('market','Hurghada',    'Tiba Mall Hurghada'),
('market','Cairo',       'Mobinil Mall Cairo'),
('market','Cairo',       'Nile City Towers Shops'),
('market','Giza',        'Pyramids Zone Market'),
('market','Cairo',       'Alf Leila Wa Leila Market'),
('market','Cairo',       'Maadi Grand Mall'),
('market','Cairo',       'Heliopolis Bazaar'),
('market','Alexandria',  'Anfushi Fish Market'),
('market','Cairo',       'Islamic Cairo Craft Stores'),
('market','Red Sea',     'Makadi Bay Resort Market'),
('market','Sinai',       'Nuweiba Bazaar'),
('market','Cairo',       'Sixth of October Mall'),
('market','Cairo',       'Dandy Mega Mall'),
('market','Cairo',       'Wadi Degla Plaza'),
('market','Cairo',       'Point 90 Mall'),
('market','Cairo',       'Waterway Market Heliopolis'),
('market','Cairo',       'Landmark Mall New Cairo'),
('market','Cairo',       'Carrefour Maadi'),
('market','Luxor',       'Luxor Papyrus Market'),
('market','Aswan',       'Aswan Spice Market'),
('market','Cairo',       'Siwa Products Market Cairo'),
('market','Cairo',       'Handicraft Bazaar Cairo'),

# ══════════════════════════ BEACH (100) ═══════════════════════════════════
('beach','South Sinai',  'Naama Bay'),
('beach','South Sinai',  'Ras Um Sid Beach'),
('beach','South Sinai',  'Shark\'s Bay Sharm'),
('beach','South Sinai',  'Hadaba Beach Sharm'),
('beach','South Sinai',  'Nabq Bay Beach'),
('beach','South Sinai',  'Turtle Beach Sharm'),
('beach','South Sinai',  'Far Garden Beach'),
('beach','South Sinai',  'Near Garden Beach'),
('beach','South Sinai',  'Ras Katy Beach'),
('beach','South Sinai',  'Fiesta Beach Sharm'),
('beach','Red Sea',      'El Gouna Beach'),
('beach','Red Sea',      'Makadi Bay Beach'),
('beach','Red Sea',      'Sahl Hasheesh Beach'),
('beach','Red Sea',      'Hurghada Beach'),
('beach','Red Sea',      'El Dahar Beach Hurghada'),
('beach','Red Sea',      'Cleopatra Beach Hurghada'),
('beach','Red Sea',      'Sigala Beach Hurghada'),
('beach','Red Sea',      'Intercontinental Beach Hurghada'),
('beach','Red Sea',      'Mamsha Beach Hurghada'),
('beach','Red Sea',      'Jasmine Beach Hurghada'),
('beach','South Sinai',  'Dahab Beach'),
('beach','South Sinai',  'Laguna Beach Dahab'),
('beach','South Sinai',  'Mashraba Beach Dahab'),
('beach','South Sinai',  'Assala Beach Dahab'),
('beach','South Sinai',  'El-Masbat Beach Dahab'),
('beach','South Sinai',  'Ras Abu Gallum Beach'),
('beach','South Sinai',  'Nuweiba Beach'),
('beach','South Sinai',  'Tarabin Beach Nuweiba'),
('beach','South Sinai',  'Soft Beach Nuweiba'),
('beach','South Sinai',  'Taba Beach'),
('beach','Matrouh',      'Cleopatra Beach Matrouh'),
('beach','Matrouh',      'Agiba Beach'),
('beach','Matrouh',      'Romeo and Juliet Beach'),
('beach','Matrouh',      'Ras El Bar Beach'),
('beach','Matrouh',      'Bir Hooker Beach'),
('beach','Matrouh',      'Lido Beach Matrouh'),
('beach','Matrouh',      'El Gharam Beach'),
('beach','Mediterranean','Alexandria Corniche Beach'),
('beach','Mediterranean','Montazah Beach Alexandria'),
('beach','Mediterranean','Mamoura Beach Alexandria'),
('beach','Mediterranean','Hannoville Beach Alexandria'),
('beach','Mediterranean','Sidi Bishr Beach'),
('beach','Mediterranean','Miami Beach Alexandria'),
('beach','Mediterranean','Stanley Beach Alexandria'),
('beach','Mediterranean','Gleem Beach Alexandria'),
('beach','Mediterranean','Sidi Abdel Rahman Beach'),
('beach','Mediterranean','Marakia Beach'),
('beach','Mediterranean','Ras El Hikma Beach'),
('beach','Red Sea',      'Marsa Alam Beach'),
('beach','Red Sea',      'Abu Dabbab Beach'),
('beach','Red Sea',      'Marsa Shona Beach'),
('beach','Red Sea',      'Wadi Lahmi Beach'),
('beach','Red Sea',      'Dolphin House Beach Hurghada'),
('beach','Red Sea',      'Paradise Beach Hurghada'),
('beach','Red Sea',      'Soma Bay Beach'),
('beach','Red Sea',      'Safaga Beach'),
('beach','Red Sea',      'El Quseir Beach'),
('beach','Red Sea',      'Port Ghalib Beach'),
('beach','South Sinai',  'Moon Beach Sharm'),
('beach','South Sinai',  'White Knight Beach Sharm'),
('beach','South Sinai',  'Gardens Beach Sharm'),
('beach','South Sinai',  'Pigeon House Beach Sharm'),
('beach','South Sinai',  'Eel Garden Beach Dahab'),
('beach','South Sinai',  'Islands Beach Dahab'),
('beach','South Sinai',  'Three Pools Dahab'),
('beach','South Sinai',  'Camel Beach Dahab'),
('beach','Red Sea',      'Giftun Island Beach'),
('beach','Red Sea',      'Orange Bay Beach'),
('beach','Red Sea',      'Magawish Island Beach'),
('beach','Red Sea',      'Fanous Reef Beach'),
('beach','South Sinai',  'Gabr El Bint Beach'),
('beach','Matrouh',      'Matrouh Corniche Beach'),
('beach','Matrouh',      'Beau Site Beach Matrouh'),
('beach','Mediterranean','North Coast Beach'),
('beach','Mediterranean','Hacienda Bay Beach'),
('beach','Mediterranean','Marassi Beach'),
('beach','Mediterranean','Marina El Alamein Beach'),
('beach','Mediterranean','Amwaj Beach North Coast'),
('beach','Mediterranean','Blanca Beach North Coast'),
('beach','Mediterranean','Diplo Beach North Coast'),
('beach','Mediterranean','Almaza Bay Beach'),
('beach','Mediterranean','Stella di Mare Beach'),
('beach','Mediterranean','Porto Marina Beach'),
('beach','Mediterranean','Ceaser Beach North Coast'),
('beach','Mediterranean','Tolip Beach'),
('beach','Red Sea',      'Mangrove Beach Marsa Alam'),
('beach','Red Sea',      'Wadi el-Gemal Beach'),
('beach','Red Sea',      'Shaab Abu Ramada Beach'),
('beach','South Sinai',  'Ras Nasrani Beach'),
('beach','South Sinai',  'Thomas Reef Beach'),
('beach','Red Sea',      'Shaab El Erg Beach Hurghada'),
('beach','Red Sea',      'Makadi Bay Water Sports Beach'),
('beach','South Sinai',  'Power Station Beach Sharm'),
('beach','Red Sea',      'El Gouna Surf Beach'),
('beach','South Sinai',  'El Fanar Beach Sharm'),

# ══════════════════════════ DESERT (100) ══════════════════════════════════
('desert','New Valley',  'White Desert National Park'),
('desert','New Valley',  'Black Desert, Egypt'),
('desert','Matrouh',     'Siwa Oasis'),
('desert','Matrouh',     'Qattara Depression'),
('desert','New Valley',  'Bahariya Oasis'),
('desert','New Valley',  'Farafra Oasis'),
('desert','New Valley',  'Dakhla Oasis'),
('desert','New Valley',  'Kharga Oasis'),
('desert','New Valley',  'Gilf Kebir'),
('desert','Giza',        'Sahara Desert Egypt'),
('desert','South Sinai', 'Sinai Desert'),
('desert','South Sinai', 'Colored Canyon, Egypt'),
('desert','South Sinai', 'Wadi Feiran'),
('desert','South Sinai', 'Ain Khudra'),
('desert','Red Sea',     'Eastern Desert Egypt'),
('desert','New Valley',  'Ain Dalla Oasis'),
('desert','Matrouh',     'Great Sand Sea'),
('desert','New Valley',  'Crystal Mountain, Egypt'),
('desert','New Valley',  'Naqb Assiut'),
('desert','New Valley',  'Ain Amur'),
('desert','South Sinai', 'Wadi Taba'),
('desert','South Sinai', 'Wadi el-Arish'),
('desert','Red Sea',     'Wadi Hammamat'),
('desert','Red Sea',     'Wadi el-Gemal'),
('desert','South Sinai', 'Wadi Nasb'),
('desert','Matrouh',     'El Alamein Desert'),
('desert','New Valley',  'Nile Valley oases'),
('desert','Giza',        'Saqqara desert'),
('desert','Red Sea',     'Mons Claudianus'),
('desert','Red Sea',     'Mons Porphyrites'),
('desert','South Sinai', 'Santa Katarina Desert'),
('desert','Matrouh',     'Siwa Desert'),
('desert','New Valley',  'Ain Khudra Valley'),
('desert','South Sinai', 'Jabal Serbal'),
('desert','New Valley',  'Wadi el-Hitan'),
('desert','New Valley',  'Faiyum Desert'),
('desert','South Sinai', 'Wadi Ghazala'),
('desert','Red Sea',     'Wadi Sharm'),
('desert','New Valley',  'Qasr el-Farafra'),
('desert','New Valley',  'Qasr Dakhla'),
('desert','New Valley',  'Qasr Kharga'),
('desert','New Valley',  'Labyrinth of Egypt'),
('desert','Giza',        'Abu Sir Desert'),
('desert','Red Sea',     'Eastern Desert Mountains'),
('desert','South Sinai', 'Feiran Desert'),
('desert','Matrouh',     'Siwa salt lakes'),
('desert','New Valley',  'Ain Guifa'),
('desert','South Sinai', 'Wadi Kid'),
('desert','Red Sea',     'Wadi Umm Hussein'),
('desert','Giza',        'Giza Plateau'),
('desert','South Sinai', 'Sharm El-Sheikh Desert'),
('desert','Matrouh',     'Marsa Matruh Desert'),
('desert','New Valley',  'Valley of the Mummies Bahariya'),
('desert','New Valley',  'Ain Beida Oasis'),
('desert','South Sinai', 'Bedouin Desert Camp Sharm'),
('desert','Red Sea',     'Hurghada Desert Safari'),
('desert','New Valley',  'Bir Wahed Siwa'),
('desert','Matrouh',     'Bir Shams Desert'),
('desert','South Sinai', 'Wadi Mukattab'),
('desert','New Valley',  'Ain Samara Oasis'),
('desert','Giza',        'Western Desert Near Cairo'),
('desert','Red Sea',     'Safaga Desert'),
('desert','South Sinai', 'Wadi Itlah'),
('desert','New Valley',  'Ain Zaytun'),
('desert','Matrouh',     'Siwa Mountain Spring'),
('desert','South Sinai', 'Desert Rose Wadi Rum Egypt'),
('desert','New Valley',  'Ain Gomma'),
('desert','Red Sea',     'Wadi el-Assiuti'),
('desert','South Sinai', 'Wadi Ferran Canyon'),
('desert','New Valley',  'Siwa Fortified Village'),
('desert','Giza',        'Memphis Desert'),
('desert','Red Sea',     'South Galala Plateau'),
('desert','Red Sea',     'North Galala Plateau'),
('desert','South Sinai', 'Taba Desert Jeep Safari'),
('desert','Matrouh',     'Siwa Lake Desert'),
('desert','New Valley',  'Ain Bahrein'),
('desert','South Sinai', 'Blue Desert Dahab'),
('desert','Red Sea',     'Wadi el-Assiuti Canyon'),
('desert','New Valley',  'Ain Qureishat'),
('desert','Giza',        'Fayoum Desert'),
('desert','South Sinai', 'Barracuda Canyon'),
('desert','New Valley',  'Siwa Ancient Ruins'),
('desert','Red Sea',     'Sinai Fox Desert'),
('desert','South Sinai', 'Ras Abu Galum Desert'),
('desert','Matrouh',     'Ain Defla Spring'),
('desert','New Valley',  'Ain Sudr Oasis'),
('desert','Red Sea',     'Sunset Desert Hurghada'),
('desert','South Sinai', 'Wadi Zaghra Canyon'),
('desert','Giza',        'Pyramid Desert Experience'),
('desert','Matrouh',     'Siwa Traditional Village'),
('desert','New Valley',  'Valley of the Golden Mummies'),
('desert','Red Sea',     'Maaza tribe desert'),
('desert','South Sinai', 'Blue Hole Desert Area'),
('desert','New Valley',  'Siwa Wadi El-Askar'),
('desert','Matrouh',     'Siwa Traditional Ecolodge'),
('desert','New Valley',  'Gilf Kebir Plateau'),
('desert','South Sinai', 'Rock Inscriptions Wadi Mukattab'),

# ══════════════════════════ RELIGIOUS (100) ═══════════════════════════════
('religious','Cairo',    'Al-Azhar Mosque'),
('religious','Cairo',    'Mosque of Muhammad Ali, Cairo'),
('religious','Cairo',    'Mosque of Ibn Tulun'),
('religious','Cairo',    'Mosque of Amr ibn al-As'),
('religious','Cairo',    'Al-Hakim Mosque'),
('religious','Cairo',    'Al-Mu\'ayyad Mosque'),
('religious','Cairo',    'Mosque-Madrassa of Sultan Hassan'),
('religious','Cairo',    'Al-Rifa\'i Mosque'),
('religious','Cairo',    'Sabil-Kuttab of Katkhuda'),
('religious','Cairo',    'Hanging Church Cairo'),
('religious','Cairo',    'Ben Ezra Synagogue'),
('religious','Cairo',    'Saint Sergius and Bacchus Church, Cairo'),
('religious','Cairo',    'Abu Serga Church Cairo'),
('religious','Cairo',    'Cathedral of the Nativity of Christ Cairo'),
('religious','Cairo',    'Church of Saint Barbara, Cairo'),
('religious','Cairo',    'Church of the Virgin Mary, Maadi'),
('religious','Cairo',    'Basilica of Our Lady of Egypt'),
('religious','Cairo',    'Saint Mark\'s Coptic Orthodox Cathedral Cairo'),
('religious','Cairo',    'Patriarchal Cathedral of Saint Mark Alexandria'),
('religious','Alexandria','Abu al-Abbas al-Mursi Mosque'),
('religious','Alexandria','El-Qaid Ibrahim Mosque'),
('religious','Alexandria','St. Mark\'s Cathedral, Alexandria'),
('religious','Alexandria','Jewish Synagogue of Alexandria'),
('religious','Alexandria','Eliyahu Hanavi Synagogue'),
('religious','Sinai',    "Saint Catherine's Monastery"),
('religious','Sinai',    'Moses Well, Sinai'),
('religious','Sinai',    'Chapel of the Burning Bush'),
('religious','Sinai',    'Wadi el-Deir Monastery'),
('religious','Luxor',    'Temple of Luxor'),
('religious','Luxor',    'Karnak Temple'),
('religious','Luxor',    'Mortuary Temple of Hatshepsut'),
('religious','Aswan',    'Philae Temple'),
('religious','Aswan',    'Kom Ombo Temple'),
('religious','Aswan',    'Nubian Temple of Kalabsha'),
('religious','Aswan',    'Temple of Dakka'),
('religious','Cairo',    'Wadi el-Natrun monasteries'),
('religious','Cairo',    'Monastery of Saint Macarius the Great'),
('religious','Cairo',    'Monastery of the Syrians'),
('religious','Cairo',    'Monastery of Saint Bishoy'),
('religious','Cairo',    'Baramous Monastery'),
('religious','Fayoum',   'Monastery of Archangel Gabriel'),
('religious','South Sinai','Monastery of Saint George Dahab'),
('religious','Red Sea',  'Monastery of Saint Anthony'),
('religious','Red Sea',  'Monastery of Saint Paul'),
('religious','Red Sea',  'Monastery of the Virgin Mary El Muharraq'),
('religious','Cairo',    'Church of the Holy Virgin in Zeitoun'),
('religious','Cairo',    'Mosque of Al-Aqmar'),
('religious','Cairo',    'Mosque of Sayyidna al-Hussein'),
('religious','Cairo',    'Sayyida Zainab Mosque'),
('religious','Cairo',    'Al-Imam al-Shafi\'i Mosque'),
('religious','Cairo',    'Quba Mosque Cairo'),
('religious','Cairo',    'Mosque of Sultan Barquq'),
('religious','Cairo',    'Aqsunqur Mosque'),
('religious','Cairo',    'Mosque of Suleiman Pasha'),
('religious','Cairo',    'Al-Ghuri Complex Mosque'),
('religious','Alexandria','Mosque of Ibrahim Terbana'),
('religious','Alexandria','Mosque of Abu al-Dardaa'),
('religious','Alexandria','Mosque of Yehia'),
('religious','Sinai',    'Greek Orthodox Church Sinai'),
('religious','Luxor',    'Temple of Mut at Karnak'),
('religious','Luxor',    'Temple of Seti I'),
('religious','Aswan',    'Temple of Esna'),
('religious','Aswan',    'Wadi el-Sebua Temple'),
('religious','Cairo',    'Mosque of Amir al-Guyushi'),
('religious','Cairo',    'Mosque of Sinan Pasha'),
('religious','Cairo',    'Mosque of Emir Shaykhun'),
('religious','Cairo',    'Mosque of Qadi Yahya'),
('religious','Cairo',    'Mosque of al-Ghuri'),
('religious','Cairo',    'Mosque of Shaikh al-Mutawalli'),
('religious','Cairo',    'Mosque of Yunus al-Dawadar'),
('religious','Cairo',    'Mosque-Madrassa of al-Salih Ayyub'),
('religious','Cairo',    'Church of Saint George, Cairo'),
('religious','Cairo',    'Greek Orthodox Patriarchate of Alexandria'),
('religious','Alexandria','Catholic Church of Alexandria'),
('religious','Sinai',    'Chapel of Saint Triphon'),
('religious','Red Sea',  'Church of Saint Anthony'),
('religious','Cairo',    'Mosque of Bashtak'),
('religious','Cairo',    'Mosque of Al-Nasir Muhammad'),
('religious','Cairo',    'Mosque of Sultan Lajin'),
('religious','Cairo',    'Mosque of Altinbugha al-Maridani'),
('religious','Cairo',    'Qalawun Complex Mosque'),
('religious','Cairo',    'Khanqah of Sultan Baybars II'),
('religious','Cairo',    'Mosque of Baybars al-Jashankir'),
('religious','Cairo',    'Mosque of the Emir Qijmas al-Ishaqi'),
('religious','Cairo',    'Mosque of Emir Taghri Bardi'),
('religious','Cairo',    'Church of the Virgin Mary Haret Zuweila'),
('religious','Cairo',    'Church of Archangel Michael Cairo'),
('religious','Alexandria','Saint Mark\'s Coptic Orthodox Cathedral'),
('religious','Luxor',    'Dendera Temple complex'),
('religious','Aswan',    'Temple of Abu Simbel'),
('religious','Cairo',    'Church of Saint Barbara Cairo'),
('religious','Cairo',    'Hanging Church of Virgin Mary'),
('religious','South Sinai','Chapel of the Holy Trinity Sharm'),
('religious','Cairo',    'Ben Ezra Synagogue Old Cairo'),
('religious','Matrouh',  'Siwa Oracle Temple of Amun'),
('religious','Cairo',    'Mosque of Amir Aqsunqur'),
('religious','Cairo',    'Mosque of Emir Sangar al-Gawli'),
('religious','Cairo',    'Mosque of Qubbet Afandina'),
('religious','Cairo',    'Mosque of Sulayman Agha'),

# ══════════════════════════ CRUISE / NILE CRUISE (100) ════════════════════
('cruise','Cairo',       'Nile River'),
('cruise','Cairo',       'Felucca sailing Nile Egypt'),
('cruise','Luxor',       'Luxor to Aswan Nile cruise'),
('cruise','Aswan',       'Aswan Nile cruise'),
('cruise','Cairo',       'Cairo Nile dinner cruise'),
('cruise','Luxor',       'Nile felucca Luxor'),
('cruise','Aswan',       'Lake Nasser cruise'),
('cruise','Cairo',       'Zamalek Nile cruise'),
('cruise','Cairo',       'Nile Maxim cruise boat'),
('cruise','Luxor',       'River Nile Luxor'),
('cruise','Aswan',       'Abu Simbel cruise'),
('cruise','Cairo',       'Nile cruise Cairo Aswan'),
('cruise','Luxor',       'MS Mayfair Nile cruise'),
('cruise','Aswan',       'MS Sun Ray Nile cruise'),
('cruise','Cairo',       'President Cairo cruise ship'),
('cruise','Luxor',       'Oberoi Zahra Nile cruise'),
('cruise','Cairo',       'Nile Goddess cruise'),
('cruise','Luxor',       'Viking Ra Nile cruise'),
('cruise','Aswan',       'Sanctuary Sun Boat IV Nile cruise'),
('cruise','Luxor',       'Sonesta Nile Goddess'),
('cruise','Cairo',       'Nile Magic cruise ship'),
('cruise','Luxor',       'River Escape Nile cruise'),
('cruise','Cairo',       'Cairo floating restaurant'),
('cruise','Luxor',       'Movenpick Nile cruise'),
('cruise','Aswan',       'Nubian Nile experience'),
('cruise','Cairo',       'Nile City cruise'),
('cruise','Luxor',       'Nile cruise Luxor Karnak'),
('cruise','Aswan',       'Aswan sunset felucca'),
('cruise','Cairo',       'Corniche el-Nil cruise'),
('cruise','Luxor',       'Valley of Kings boat tour'),
('cruise','Red Sea',     'Red Sea snorkeling cruise'),
('cruise','Red Sea',     'Red Sea diving boat trip'),
('cruise','Red Sea',     'Hurghada glass bottom boat'),
('cruise','Red Sea',     'Giftun Island boat trip'),
('cruise','South Sinai', 'Sharm El Sheikh boat trip'),
('cruise','South Sinai', 'Ras Muhammad snorkel cruise'),
('cruise','South Sinai', 'Dahab boat dive trip'),
('cruise','Red Sea',     'Marsa Alam liveaboard'),
('cruise','Red Sea',     'El Gouna boat trip'),
('cruise','Red Sea',     'Soma Bay diving boat'),
('cruise','South Sinai', 'Tiran Island boat tour'),
('cruise','Cairo',       'Isis Nile cruise ship'),
('cruise','Cairo',       'Nile Star cruise'),
('cruise','Luxor',       'MS Champollion cruise'),
('cruise','Aswan',       'Sudan border Lake Nasser'),
('cruise','Cairo',       'Cairo to Luxor cruise'),
('cruise','Luxor',       'Luxor balloon over Nile'),
('cruise','Cairo',       'Aziza Nile cruise'),
('cruise','Luxor',       'MS Salacia Nile cruise'),
('cruise','Aswan',       'MS Kasr Ibrim Lake Nasser'),
('cruise','Cairo',       'Nile cruise dinner show'),
('cruise','Luxor',       'Nile cruise sunset Luxor'),
('cruise','Aswan',       'Aswan to Luxor felucca'),
('cruise','Cairo',       'Nile Pharaoh cruise boat'),
('cruise','Luxor',       'Aida Prima Nile cruise'),
('cruise','Cairo',       'Blue Shadow Nile cruise'),
('cruise','Luxor',       'Sonesta Moon Goddess'),
('cruise','Aswan',       'Belle Epoque Lake Nasser'),
('cruise','Cairo',       'The Nile Cruiser Houseboat'),
('cruise','Luxor',       'MS Amarco I Nile cruise'),
('cruise','Aswan',       'MS Eugenie Lake Nasser'),
('cruise','Red Sea',     'Red Sea Liveaboard Hurghada'),
('cruise','South Sinai', 'Sharm Dolphin Watch Cruise'),
('cruise','Red Sea',     'Dolphin House snorkel trip Hurghada'),
('cruise','Red Sea',     'Paradise Island Boat Hurghada'),
('cruise','South Sinai', 'Stargazing boat trip Dahab'),
('cruise','Cairo',       'Nile Happy Cruise'),
('cruise','Luxor',       'MS Nile Monarch'),
('cruise','Aswan',       'Nubian houseboat stay'),
('cruise','Cairo',       'Nile Safari boat'),
('cruise','Red Sea',     'Hurghada submarine tour'),
('cruise','South Sinai', 'Sinai coastline cruise'),
('cruise','Red Sea',     'El Quseir liveaboard'),
('cruise','Luxor',       'Nile Valley cruise Abydos'),
('cruise','Aswan',       'Assuan houseboat dinner'),
('cruise','Cairo',       'Nile cruising Cairo all inclusive'),
('cruise','Red Sea',     'Safaga snorkel cruise'),
('cruise','South Sinai', 'Naama Bay sunset cruise'),
('cruise','Red Sea',     'Magawish Island cruise'),
('cruise','Cairo',       'Nile Taxi Maadi'),
('cruise','Luxor',       'East West Bank ferry Luxor'),
('cruise','Cairo',       'Giza Nile cruise'),
('cruise','Red Sea',     'Hurghada party boat'),
('cruise','South Sinai', 'Aqaba Gulf sailing'),
('cruise','Luxor',       'MS Sudan Nile cruise'),
('cruise','Aswan',       'Cataract Nile view boat'),
('cruise','Cairo',       'Zamalek sailing club'),
('cruise','Red Sea',     'Quseir to Safaga dive boat'),
('cruise','South Sinai', 'Dahab reef liveaboard'),
('cruise','Cairo',       'Thursday night Nile boat'),
('cruise','Luxor',       'Nile cruise Winter Palace'),
('cruise','Aswan',       'Nubian sunrise felucca'),
('cruise','Red Sea',     'Orange Bay cruise'),
('cruise','South Sinai', 'Blue Hole dive boat'),
('cruise','Cairo',       'Floating restaurant Cairo Nile'),
('cruise','Luxor',       'Nile heritage cruise'),
('cruise','Aswan',       'Sehel Island boat trip'),
('cruise','Red Sea',     'Giftun South Island cruise'),
('cruise','South Sinai', 'Ras Nasrani diving boat'),
]

# ─────────────────────────────────────────────────────────────────────────────
def get_db(): return pyodbc.connect(DB_CONN_STR)
def count_cat(cur, cat):
    cur.execute("SELECT COUNT(*) FROM Places WHERE category=?", cat)
    return cur.fetchone()[0]
def exists(cur, name):
    cur.execute("SELECT COUNT(*) FROM Places WHERE name_en=?", name)
    return cur.fetchone()[0] > 0

def translate_ar(text):
    if not text or len(text.strip()) < 3: return text
    try: return GoogleTranslator(source='en', target='ar').translate(text[:4500])
    except: return text

def wiki_get(title):
    """Fetch Wikipedia page data (description + thumbnail + coordinates)"""
    try:
        r = requests.get(WIKI_API, params={
            'action':'query','titles':title,
            'prop':'extracts|pageimages|coordinates',
            'exintro':True,'exsentences':5,
            'piprop':'thumbnail|original','pithumbsize':1200,
            'format':'json','redirects':True,
        }, headers=HEADERS, timeout=12)
        if r.status_code != 200: return None
        pages = r.json().get('query',{}).get('pages',{})
        p = list(pages.values())[0]
        if p.get('pageid',-1) < 0: return None
        return p
    except: return None

def wiki_images(title, want=3):
    """Get image URLs from a Wikipedia article"""
    imgs = []
    try:
        r = requests.get(WIKI_API, params={
            'action':'query','titles':title,'prop':'images',
            'imlimit':20,'format':'json','redirects':True,
        }, headers=HEADERS, timeout=10)
        if r.status_code != 200: return imgs
        pages = r.json().get('query',{}).get('pages',{})
        p = list(pages.values())[0]
        img_list = [i['title'] for i in p.get('images',[])
                    if not any(x in i['title'].lower()
                               for x in ['svg','logo','flag','icon','map','stub',
                                         'portal','commons','red_x','edit'])]
        for fname in img_list[:want*3]:
            url = commons_url(fname.replace('File:',''))
            if url: imgs.append(url)
            if len(imgs) >= want: break
    except: pass
    return imgs

def commons_url(filename):
    try:
        r = requests.get(COMMONS_API, params={
            'action':'query','titles':'File:'+filename,
            'prop':'imageinfo','iiprop':'url','iiurlwidth':1200,
            'format':'json',
        }, headers=HEADERS, timeout=8)
        if r.status_code != 200: return None
        pages = r.json().get('query',{}).get('pages',{})
        p = list(pages.values())[0]
        info = p.get('imageinfo',[])
        if info:
            url = info[0].get('thumburl') or info[0].get('url','')
            if url and any(url.lower().endswith(e) for e in ['.jpg','.jpeg','.png','.webp']):
                return url
    except: pass
    return None

def clean_html(text):
    import html
    text = re.sub(r'<[^>]+>','', text)
    text = html.unescape(text)
    return re.sub(r'\s+',' ', text).strip()

def infer_gov(name, title, default):
    al = (name+' '+title).lower()
    for k, v in GOV_MAP.items():
        if k in al: return v
    return default

def insert_place(cur, cat, gov, d):
    o_open, o_close = OPEN_MAP.get(cat, ('09:00','18:00'))
    cur.execute("""
        INSERT INTO Places(name_en,name_ar,description_en,description_ar,
            category,governorate,latitude,longitude,address,
            admission_fee_egyptian,admission_fee_foreign,
            opening_hours_open,opening_hours_close,opening_hours_days,
            tags,is_featured,avg_rating,review_count,
            rating_1,rating_2,rating_3,rating_4,rating_5,created_at)
        OUTPUT INSERTED.id VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,GETDATE())
    """,
    d['name_en'],d['name_ar'],d['desc_en'],d['desc_ar'],
    cat,gov,d['lat'],d['lng'],d.get('addr',gov+', Egypt')[:299],
    0.0,0.0,o_open,o_close,'Daily',
    TAGS_MAP.get(cat,'Egypt'),d['rating']>=4.5,d['rating'],0,
    0,0,0,0,0)
    return cur.fetchone()[0]

def insert_imgs(cur, pid, imgs):
    for i,u in enumerate(imgs[:3]):
        if u and u.startswith('http'):
            cur.execute("INSERT INTO PlaceImages(place_id,image_url,sort_order)"
                        "VALUES(?,?,?)", pid, u, i)

# ─────────────────────────────────────────────────────────────────────────────
def main():
    print("="*65)
    print("Egypt Mega Scraper (Wikipedia) - 100 per category")
    print("="*65)
    conn = get_db(); cursor = conn.cursor()
    total = 0

    for cat, default_gov, wiki_title in EGYPT_PLACES:
        current = count_cat(cursor, cat)
        if current >= TARGET:
            continue   # category done, skip

        print(f"\n[{current}/{TARGET}] {cat.upper()} | {default_gov} | {wiki_title[:50]}")

        # Get Wikipedia data
        page = wiki_get(wiki_title)
        if page:
            name  = page.get('title', wiki_title)
            desc  = clean_html(page.get('extract',''))
            desc  = ' '.join(re.split(r'(?<=[.!?])\s+', desc)[:5])[:1500]
            coords = page.get('coordinates', [])
            lat   = float(coords[0]['lat']) if coords else 0.0
            lng   = float(coords[0]['lon']) if coords else 0.0
            # Thumbnail first
            imgs = []
            thumb_orig = page.get('thumbnail',{}).get('original','')
            if thumb_orig and any(thumb_orig.lower().endswith(e)
                                  for e in ['.jpg','.jpeg','.png']):
                imgs.append(thumb_orig)
            # More images from article
            if len(imgs) < 3:
                more = wiki_images(wiki_title, 3-len(imgs))
                imgs.extend(more)
        else:
            name  = wiki_title
            desc  = f"A wonderful {cat} destination in {default_gov}, Egypt."
            lat, lng = 0.0, 0.0
            imgs  = []

        if not desc or len(desc) < 20:
            desc = f"A remarkable {cat} destination in {default_gov}, Egypt."

        name = name[:299]
        if exists(cursor, name):
            print(f"  Exists: {name[:45]}"); continue

        print(f"  Name: {name[:55]}")
        print(f"  Imgs: {len(imgs)}")
        print(f"  Translating...")

        name_ar = translate_ar(name)
        desc_ar = translate_ar(desc[:500])
        gov = infer_gov(name, wiki_title, default_gov)

        data = dict(
            name_en=name, name_ar=name_ar[:299],
            desc_en=desc[:3000], desc_ar=desc_ar[:3000],
            lat=lat, lng=lng, addr=gov+', Egypt', rating=4.2,
        )
        try:
            pid = insert_place(cursor, cat, gov, data)
            insert_imgs(cursor, pid, imgs)
            conn.commit(); total += 1
            print(f"  [OK] ID:{pid}")
        except Exception as e:
            conn.rollback(); print(f"  [ERR] {e}")

        time.sleep(random.uniform(0.3, 0.8))   # respect Wikipedia

    print(f"\n{'='*65}")
    print(f"[DONE] Added: {total} places")
    for cat in ['historical','museum','hotel','nature','market',
                'beach','desert','religious','cruise']:
        print(f"  {cat:12}: {count_cat(cursor, cat)}/100")
    cursor.close(); conn.close()
    print("="*65)

if __name__ == '__main__':
    main()
